# Generated by Django 3.0.7 on 2020-06-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.CharField(default='My profile description', max_length=300),
        ),
    ]
